@startuml
title Thêm thông tin xe - Sequence Diagram
actor "Người Dùng" as user
participant "Hệ Thống" as system
database "Cơ Sở Dữ Liệu" as database

activate user
user -> system: Nhập Thông Tin Xe Ô Tô
activate system
system -> system: Xác Nhận Thông Tin Xe Ô Tô
system -> database: Lưu Thông Tin Xe Ô Tô vào Cơ Sở Dữ Liệu
activate database
database --> system: Xác Nhận Lưu Thông Tin
deactivate database
system --> user: Hiển Thị Kết Quả (Thành Công hoặc Lỗi)
deactivate user
deactivate system
@enduml