@startuml
title Đăng Ký Người Dùng và Xác Nhận Đăng Nhập - Sequence Diagram

actor "Khách hàng" as user
participant "Hệ Thống" as system
database "Cơ Sở Dữ Liệu" as database

activate user
user -> system: Nhập Thông Tin Đăng Ký (Tên Đăng Nhập, Mật Khẩu, Email)
activate system
system -> database: Kiểm Tra Tên Đăng Nhập và Email (để đảm bảo không trùng lặp)
activate database
database --> system: Truy vấn Cơ Sở Dữ Liệu
deactivate database
system --> user: Xác Nhận Đăng Ký Thành Công hoặc Báo Lỗi


user -> system: Nhập Tên Đăng Nhập và Mật Khẩu (để xác nhận đăng nhập)
system -> database: Truy vấn Tên Đăng Nhập và Mật Khẩu
activate database
database --> system: Kiểm Tra Tên Đăng Nhập và Mật Khẩu
deactivate database
system --> user: Xác Nhận Đăng Nhập Thành Công hoặc Thất Bại
deactivate system
deactivate user
@enduml
