@startuml
title Xem hồ sơ - Sequence Diagram

actor "Người Dùng" as user
participant "Hệ Thống" as system
database "Cơ Sở Dữ Liệu" as database

activate user
user -> system: Yêu Cầu Xem Hồ Sơ
activate system
system -> database: Truy vấn Hồ Sơ Người Dùng
activate database
database --> system: Trả về Hồ Sơ Người Dùng
deactivate database
system --> user: Hiển Thị Hồ Sơ Người Dùng



deactivate system
deactivate user
@enduml
