@startuml
title Chỉnh sửa hồ sơ  - Sequence Diagram

actor "Người Dùng" as user
participant "Hệ Thống" as system
database "Cơ Sở Dữ Liệu" as database

user -> system: Yêu Cầu Chỉnh Sửa Hồ Sơ (Thông tin mới)
activate system
system -> database: Cập Nhật Thông Tin Hồ Sơ
activate database
database --> system: Lưu Thông Tin Hồ Sơ Mới
deactivate database
system --> user: Xác Nhận Chỉnh Sửa Hồ Sơ Thành Công



deactivate system
deactivate user
@enduml