@startuml
title Thanh Toán Trả Góp - Sequence Diagram

actor "Người Dùng" as user
participant "Hệ Thống" as system
participant "Dịch vụ tài chính" as externalPaymentSystem
database "Cơ Sở Dữ Liệu" as database

activate user
user -> system: Yêu Cầu Thanh Toán (transactionId, amount)
activate system
system -> database: Truy vấn Giao Dịch (transactionId)
activate database
database --> system: Trả Về Thông Tin Giao Dịch
deactivate database
system -> externalPaymentSystem: Yêu Cầu Thanh Toán Bên Ngoài (transactionId, amount)
activate externalPaymentSystem
externalPaymentSystem --> externalPaymentSystem: Xử Lý Thanh Toán
externalPaymentSystem --> system: Kết Quả Thanh Toán
deactivate externalPaymentSystem
system -> system: Xác Nhận thanh toán đủ
system -> database: Cập nhật trạng thái giao dịch của hợp đồng
activate database
database --> system: Xác nhập cập nhật giao dịch
deactivate database
system --> user: Xuất Hóa Đơn và Thông Tin Thanh Toán

deactivate system
deactivate user
@enduml
