@startuml
actor NgườiDùng
participant HệThống
NgườiDùng -> HệThống: Chọn Xe Cần Sửa
activate HệThống
HệThống -> HệThống: Truy vấn thông tin xe từ CSDL
HệThống -> NgườiDùng: Hiển thị thông tin xe cần sửa
NgườiDùng -> HệThống: Sửa Thông Tin Xe
activate HệThống
HệThống -> HệThống: Cập nhật thông tin xe vào CSDL
HệThống --> NgườiDùng: Hiển thị thông báo "Thông Tin Xe Đã Được Sửa"
deactivate HệThống
@enduml
