@startuml
left to right direction
skinparam linetype ortho

'Create actor
actor :Manager: as AManager
actor :Sales Agent: as AEmployee
actor :Customer: as ACustomer
actor :Online Payment System: as APayment
actor :Finacial Support Service Unit: as APaymentSupport
actor :Shipping Services: as AShippingService
actor :Integrate Insurance Services: as AIntegrateInsuranceServices
actor :Maintenance Services: as AMaintenanceServices
AManager --|> AEmployee

'Create Login Usecase 
usecase "Login" as ULogin 
ACustomer --> ULogin
AEmployee --> ULogin
note bottom of ULogin
    Customer, Sales Agent, Manager have to login the system before using functions.
end note

'Create Register Usecase 
usecase "Register" as URegister
ACustomer --> URegister
note bottom of URegister
    Customer have to register to the system before using functions.
end note


'Create Manage Car Usecase
usecase "Manage Cars" as UManageCars 
AManager --> UManageCars

'Create Transactions Usecase 
usecase "Manage Transactions and Contracts" as UManageTransactions
ACustomer --> UManageTransactions
AEmployee --> UManageTransactions

'Create Manage User Information Usecase
usecase "Manage User Informations" as UManageUserInfos
ACustomer --> UManageUserInfos
AManager --> UManageUserInfos

'Create View Car Infomation Usecase
usecase "View Car Information" as UViewCarInfo
ACustomer --> UViewCarInfo
AEmployee --> UViewCarInfo 
 
'Create Pay Deposit/Purchase money Usecase
usecase "Pay Deposit/Purchase money" as UPay 
ACustomer --> UPay
UPay --> APayment
UPay --> APaymentSupport


'Create Statistics and Reporting UseCase
usecase "Statistics and Reporting" as UStatisticsandReporting
AEmployee --> UStatisticsandReporting

'Create Integrate Shipping Services and Related Services UseCase
usecase "Integrate Shipping Services and Related Services" as URelatedServices
AEmployee --> URelatedServices
ACustomer --> URelatedServices
AIntegrateInsuranceServices <-- URelatedServices
AShippingService <-- URelatedServices
AMaintenanceServices <-- URelatedServices
@enduml