@startuml
left to right direction
actor "Người Dùng" as user
rectangle "Hệ Thống" {
  usecase "Tìm Kiếm Xe Ô Tô" as search
  usecase "Xem Chi Tiết Xe Ô Tô" as viewDetails
}

user --> search 
user --> viewDetails 

search ..> (Hiển Thị Kết Quả Tìm Kiếm) : <<include>>
search ..> (Lọc Kết Quả Tìm Kiếm) : <<include>>
(Hiển Thị Kết Quả Tìm Kiếm) ..> viewDetails : <<extend>>
@enduml