@startuml
left to right direction
skinparam linetype ortho
actor "Người Dùng" as user
rectangle "Hệ Thống" {
  usecase "Đăng Nhập" as login
  usecase "Đăng Ký" as register
  usecase "Quản Lý Hồ Sơ" as manageProfile
  usecase "Quên Mật Khẩu" as forgotPassword
}

user --> login 
user --> register 
user --> manageProfile
user --> forgotPassword

manageProfile ..> (Xem Hồ Sơ) : <<extend>>
manageProfile ..> (Chỉnh Sửa Hồ Sơ) : <<extend>>
manageProfile ..> (Đổi Mật Khẩu) : <<extend>>
@enduml