@startuml
left to right direction
actor "Người Dùng" as user
rectangle "Hệ Thống" {
  usecase "Đặt Lịch Hẹn Xem Xe" as scheduleAppointment
  usecase "Xác Nhận Lịch Hẹn" as confirmAppointment
  usecase "Hủy Lịch Hẹn" as cancelAppointment
}

user --> scheduleAppointment 
scheduleAppointment --> confirmAppointment 
scheduleAppointment --> cancelAppointment 

confirmAppointment ..> (Gửi Xác Nhận) : <<include>>
cancelAppointment ..> (Xác Nhận Hủy Lịch Hẹn) : <<include>>
@enduml