@startuml
left to right direction
actor "Nhân Viên/Quản lí" as employee
rectangle "Quản lí thông tin xe oto" {
  usecase "CURD Hãng xe" as curdBrand
  usecase "CURD Dòng xe" as curdModel
  usecase "CURD Thông tin xe tiết" as curdInfo 
  usecase "CURD Số lượng xe tồn" as curdQuantity

  curdBrand ..> (Kiểm tra định dạng dữ liệu) : <<include>>
  curdModel ..> (Kiểm tra định dạng dữ liệu) : <<include>>
  curdInfo ..> (Kiểm tra định dạng dữ liệu) : <<include>>
  curdQuantity ..> (Kiểm tra định dạng dữ liệu) : <<include>>
}

employee --> curdBrand
employee --> curdModel
employee --> curdInfo
employee --> curdQuantity

@enduml