@startuml
left to right direction
actor "Người Quản Lý" as manager
rectangle "Hệ Thống" {
  usecase "Thêm Nhân Viên" as addEmployee
  usecase "Sửa Thông Tin Nhân Viên" as editEmployee
  usecase "Xóa Nhân Viên" as deleteEmployee
}

manager --> addEmployee
manager --> editEmployee
manager --> deleteEmployee

addEmployee ..> (Xác Nhận Thêm) : <<include>>
editEmployee ..> (Xác Nhận Sửa) : <<include>>
deleteEmployee ..> (Xác Nhận Xóa) : <<include>>
@enduml