@startuml
left to right direction
actor "Người Quản Lý" as manager
rectangle "Hệ Thống" {
  usecase "Quản Lý Dữ Liệu Người Dùng" as manageUserData
  usecase "Quản Lý Dữ Liệu Xe Ô Tô" as manageCarData
  usecase "Tích Hợp Dịch Vụ Vận Chuyển" as integrateShippingService
  usecase "Tích Hợp Dịch Vụ Bảo Hiểm" as integrateInsuranceService
  usecase "Tích Hợp Dịch Vụ Bảo Dưỡng" as integrateMaintenanceService
}

manager --> manageUserData
manager --> manageCarData
manager --> integrateShippingService
manager --> integrateInsuranceService
manager --> integrateMaintenanceService

manageUserData ..> (Thực Hiện Cập Nhật) : <<extend>>
manageCarData ..> (Thực Hiện Cập Nhật): <<extend>>
integrateShippingService ..> (Xác Nhận Tích Hợp): <<include>>
integrateInsuranceService ..> (Xác Nhận Tích Hợp): <<include>>
integrateMaintenanceService ..> (Xác Nhận Tích Hợp): <<include>>
@enduml