@startuml
|Người Dùng|
start
:Chọn Xem Hồ Sơ Người Dùng;
|Hệ Thống|
if (Yêu Cầu Được Chọn?) then (Có)
  :Truy Vấn Hồ Sơ Người Dùng từ Cơ Sở Dữ Liệu;
  if (Hồ Sơ Tồn Tại?) then (Có)
    :Hiển Thị Hồ Sơ Người Dùng;
  else (Không)
    :Hiển Thị Thông Báo "Hồ Sơ Người Dùng Không Tồn Tại";
  endif
else (Không)
  :Hiển Thị Thông Báo "Vui Lòng Chọn Hồ Sơ Người Dùng";
endif
|Người Dùng|
stop
@enduml
