@startuml
|Người Dùng|
start
:Chọn Quên Mật Khẩu;
|Hệ Thống|
if (Yêu Cầu Được Chọn?) then (Có)
    :Hiển Thị Form nhập Email Xác Thực;
    |Người Dùng|
    :Người Dùng Nhập Email để xác thực;
    |Hệ Thống|
    :Gửi code xác nhận về Email;
    |Người Dùng|
    :Nhập code xác thực;
    |Hệ Thống|
    :Kiểm Tra code Xác Thực Hợp Lệ?;
    if (Code xác thực Hợp Lệ?) then (Có)
        :Hiển Thị Form nhập mật khẩu mới;
        |Người Dùng|
        :Người Dùng Nhập Mật khẩu mới;
        |Hệ Thống|
        if (Kiểm tra mật khẩu hợp lệ?) then (Có)
            :Lưu thông tin về database;
            if (Lưu Thành Công?) then (Có)
                :Hiển Thị Thông Báo "Mật Khẩu Đã Được Đổi";
            else (Không)
                :Hiển Thị Thông Báo "Lỗi: Không Thể Lưu Mật Khẩu Mới";
            endif
        else
            :Thông báo: "Mật khẩu mới không hợp lệ";
        endif
    else (Không)
        :Hiển Thị Thông Báo "Lỗi: Code Xác Thực Không Hợp Lệ";
    endif
|Hệ Thống|
else (Không)
endif
stop
@enduml


