@startuml
|Người Dùng|
start
:(1)Chọn Lịch Hẹn Cần Hủy;
|Hệ Thống|
:(2)Hiển thị thông tin lịch hẹn;
|Người Dùng|
:(3)Người Dùng Xác Nhận Hủy Lịch Hẹn;
|Hệ Thống|
if ((4)Xác Nhận Hủy?) then (Có)
  :(5.1)Kiểm Tra Lịch Hẹn;
  if ((6)Lịch Hẹn Tồn Tại?) then (Có)
    :(7.1)Hủy Lịch Hẹn trong Cơ Sở Dữ Liệu;
    if ((8)Hủy Thành Công?) then (Có)
      :(9.1)Hiển Thị Thông Báo "Lịch Hẹn Đã Được Hủy";
    else (Không)
      :(9.2)Hiển Thị Thông Báo "Lỗi: Không Thể Hủy Lịch Hẹn";
    endif
  else (Không)
    :(7.2)Hiển Thị Thông Báo "Lịch Hẹn Không Tồn Tại";
  endif
  |Hệ Thống|
else (Không)
  :(5.2)Hiển Thị Thông Báo "Hủy Lịch Hẹn Đã Bị Hủy";
endif
stop
@enduml
