@startuml
title Xóa Thông Tin Xe Ô Tô - Activity Diagram

|Người Dùng|
start
:Chọn Xe Muốn Xóa Thông Tin;
|Hệ Thống|
if (Người Dùng Chọn Xe Muốn Xóa Thông Tin?) then (yes)
  :Hiển Thị Xác Nhận Xóa Thông Tin Xe Ô Tô;
  if (Người Dùng Xác Nhận Muốn Xóa?) then (yes)
    :Xóa Thông Tin Xe Ô Tô Khỏi Cơ Sở Dữ Liệu;
    :Xác Nhận Xóa Thông Tin Xe Ô Tô Thành Công;
  else (no)
    :Hiển Thị Thông Báo Xóa Thông Tin Bị Hủy;
  endif
else (no)
endif
stop
@enduml