@startuml
title Chuẩn Bị Xe Giao Dịch - Activity Diagram

|Nhân Viên|
start
:Chọn Xe Muốn Chuẩn Bị Giao Dịch;
|Hệ Thống|
if (Người Dùng Chọn Xe Muốn Chuẩn Bị Giao Dịch?) then (yes)
  :Hiển Thị Form Chi Tiết Xe Để Chuẩn Bị Giao Dịch;
  |Nhân Viên|
  :Kiểm Tra Chi Tiết Xe, Chuẩn Bị Giấy Tờ và Phương Tiện;
  :Xác Nhận Đã Kiểm Tra;
  |Hệ Thống|
  if (Chuẩn Bị Hoàn Tất?) then (yes)
    :Xác Nhận Chuẩn Bị Giao Dịch;
    :Gửi Thông Tin Chuẩn Bị Giao Dịch Đến Cơ Sở Dữ Liệu;
    :Xác Nhận Chuẩn Bị Giao Dịch Thành Công;
  else (no)
    :Hiển Thị Thông Báo Chuẩn Bị Giao Dịch Không Hoàn Tất;
  endif
else (no)
endif
stop
@enduml
