@startuml
title Tạo Báo Cáo - Activity Diagram

|Nhân Viên và Quản Lí|
start
:Chọn Loại Báo Cáo Muốn Tạo;
|Hệ Thống|
if (Người Dùng Chọn Loại Báo Cáo?) then (yes)
  :Hiển Thị Form Tạo Báo Cáo;
  |Nhân Viên và Quản Lí|
  :Nhập Thêm Một Số Thông Tin Cần Thiết;
  :Xác Nhận Hoàn Tất Tạo Báo Cáo;
  |Hệ Thống|
  :Tạo Báo Cáo Dựa Trên Thông Tin Nhập Vào và Thông Tin Truy Vấn Từ CSDL;
  :Xác Nhận Tạo Báo Cáo Thành Công;
else (no)
endif
stop
@enduml
