@startuml
title Xóa Thông Tin Nhân Viên - Activity Diagram

|Nhân Viên Quản Lý|
start
:Chọn Chức Năng "Xóa Thông Tin Nhân Viên";
|Hệ Thống|
if (Nhân Viên Quản Lý Chọn Chức Năng "Xóa Thông Tin Nhân Viên"?) then (yes)
  :Yêu Cầu ID hoặc Tên Nhân Viên Cần Xóa Thông Tin;
  |Nhân Viên Quản Lý|
  :Nhập ID hoặc Tên Nhân Viên;
  |Hệ Thống|
  :Hiển Thị Thông Tin Chi Tiết Của Nhân Viên;
  :Xác Nhận Yêu Cầu Xóa Thông Tin;
  |Nhân Viên Quản Lý|
  :Xác Nhận Xóa;
  |Hệ Thống|
  :Xóa Thông Tin Nhân Viên và Xác Nhận Thành Công;
else (no)
endif
stop
@enduml
