@startuml
title Thêm Nhân Viên - Activity Diagram

|Nhân Viên Quản Lý|
start
:Chọn Chức Năng "Thêm Nhân Viên";
|Hệ Thống|
if (Nhân Viên Quản Lý Chọn Chức Năng "Thêm Nhân Viên"?) then (yes)
  :Yêu Cầu Thông Tin Chi Tiết Của Nhân Viên Mới;
  |Nhân Viên Quản Lý|
  :Nhập Thông Tin Chi Tiết;
  |Hệ Thống|
  :Lưu Thông Tin Nhân Viên Và Xác Nhận Thành Công;
else (no)
  stop
endif
|Nhân Viên Quản Lý|
stop
@enduml
